#!/usr/bin/env python
#
# /// pyproject
# [project]
# dependencies = [
#     "numpydoc",
#     "rst-to-myst"
# ]

import argparse
import inspect
from numpydoc.docscrape import NumpyDocString, Parameter
import sys
import types
import json

import rst_to_myst


def is_submodule(child: types.ModuleType, parent: types.ModuleType) -> bool:
    return child.__name__.startswith(parent.__name__ + ".")


def rst2myst(rst: str | list) -> str:
    if isinstance(rst, list):
        rst = "\n".join(rst)

    return rst_to_myst.mdformat_render.rst_to_myst(rst).text.strip()


def walk_mod(mod: types.ModuleType, path: str = "") -> dict:
    members_names = mod.__all__
    out = {}

    for member_name in members_names:
        print("\033[0K", end="\r", file=sys.stderr)  # Clear line
        print(f"{path}.{member_name}", end="\r", file=sys.stderr)

        member = getattr(mod, member_name)

        if inspect.isfunction(member):
            if member.__doc__:
                out[member_name] = dict(NumpyDocString(member.__doc__))
                npdoc = out[member_name]

                rst_fields = ["Extended Summary", "Notes"]
                for field in rst_fields:
                    if npdoc.get(field):
                        npdoc[field] = rst2myst(npdoc[field])

                for key, val in npdoc.items():
                    if isinstance(val, list) and len(val) > 0:
                        # Unpack parameter list
                        if isinstance(val[0], Parameter):
                            npdoc[key] = [
                                {
                                    "name": el.name,
                                    "type": el.type,
                                    "desc": rst2myst(el.desc),
                                }
                                for el in val
                            ]

        if inspect.ismodule(member) and is_submodule(member, mod):
            out[member_name] = walk_mod(member, path=path + "." + member_name)

    return out


if __name__ == "__main__":
    YELLOW = "\033[1;33m"
    RESET = "\033[0m"

    parser = argparse.ArgumentParser(
        prog="fleece",
        description=f"{YELLOW}🟨{RESET} Fleece extracts a Python package's numpydoc-formatted docstrings as JSON. "
        "Currently, this is for use by the myst-apidoc-plugin only.",
    )
    parser.add_argument("package", help="The package to index")
    args = parser.parse_args()

    pkgname = args.package
    pkg = __import__(pkgname)

    print(json.dumps(walk_mod(pkg, path=pkgname)))
